language: python
# make it explicit that we favor the new container-based travis workers
sudo: false
# addons:
#   apt:
#     packages:
#       - python2.7


matrix:
  include:
    - python: 2.7
    - python: 3.4
    - python: 3.5
    - python: 3.6
    - python: "nightly"
    - os: osx
      osx_image: xcode7.3
      language: generic  # https://github.com/travis-ci/travis-ci/issues/2312
      cache:
        # As for now travis caches only "$HOME/.cache/pip"
        # https://docs.travis-ci.com/user/caching/#pip-cache
        pip: false
        directories:
          - $HOME/Library/Caches/pip
          # `cache` does not support `env`-like `global` so copy-paste from top
          - $HOME/.ccache  # https://github.com/travis-ci/travis-ci/issues/5853
  allow_failures:
    - python: "nightly"


before_install:
  - |
    # Install into our own pristine virtualenv
    if [[ $TRAVIS_OS_NAME != 'osx' ]]; then
      echo "nothing done"
    else
      brew update
      brew tap homebrew/gui
      brew install python
      pip install tox pytest
    fi

install: source continuous_integration/install.sh
script: bash continuous_integration/test_script.sh
# after_success:
#     # Ignore coveralls failures as the coveralls server is not very reliable
#     # but we don't want travis to report a failure in the github UI just
#     # because the coverage report failed to be published.
#     - if [[ "$COVERAGE" == "true" ]]; then coveralls || echo "failed"; fi
notifications:
  webhooks:
    on_success: change
    # options: [always|never|change] default: always
    on_failure: always
    # options: [always|never|change] default: always
    on_start: never
    # options: [always|never|change] default: always
