# language: python
# make it explicit that we favor the new container-based travis workers
sudo: false
# addons:
#   apt:
#     packages:
#       - python2.7

env:
  - PYTHON="python"
  - TRAVIS_TESTING=1


matrix:
  include:
    - python: 2.7
    - python: 3.3
    - python: 3.4
    - python: 3.5
    - python: "nightly"
    - os: osx
      osx_image: xcode7.3
      language: generic  # https://github.com/travis-ci/travis-ci/issues/2312
    - os: osx
      osx_image: xcode7.3
      language: generic  # https://github.com/travis-ci/travis-ci/issues/2312
      env: PYTHON="python3"


before_install:
  - |
    # Install python using brew on OSX
    if [[ $TRAVIS_OS_NAME == 'osx' ]]; then
      brew update
      brew install $PYTHON
    fi

install: ./continuous_integration/install.sh
script: ./continuous_integration/test_script.sh
# after_success:
#     # Ignore coveralls failures as the coveralls server is not very reliable
#     # but we don't want travis to report a failure in the github UI just
#     # because the coverage report failed to be published.
#     - if [[ "$COVERAGE" == "true" ]]; then coveralls || echo "failed"; fi
notifications:
  webhooks:
    on_success: change
    # options: [always|never|change] default: always
    on_failure: always
    # options: [always|never|change] default: always
    on_start: never
    # options: [always|never|change] default: always
